package:
  name: gsva-python-cli
  version: "1.0.4"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/GSVA.git

build:
  number: 4

requirements:
  build:
    - python 3.6.*
    - setuptools
  run:
    - python 3.6.*
    - bioconductor-gseabase 1.40.0
    - bioconductor-gsva 1.26.0
    - setuptools

about:
  home: https://github.com/jason-weirather/GSVA
  license: Apache 2.0
  license_file: LICENSE
