package:
  name: gsva-python-cli
  version: "1.0.1"

source:
  git_rev: master
  git_url: https://github.com/jason-weirather/GSVA.git

build:
  number: 2

requirements:
  build:
    - python 3.6.*
    - r-essentials
    - setuptools
  run:
    - python 3.6.*
    - r-essentials
    - setuptools

about:
  home: https://github.com/jason-weirather/GSVA
  license: Apache 2.0
  license_file: LICENSE
